-- Creazione della tabella clienti
CREATE TABLE clienti (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  cognome VARCHAR(50) NOT NULL,
  citta VARCHAR(50),
  email VARCHAR(100) UNIQUE
);

-- Inserimento di dati nella tabella clienti (50 record)
INSERT INTO clienti (nome, cognome, citta, email) VALUES
('Mario', 'Rossi', 'Roma', 'mario.rossi@example.com'),
('Giulia', 'Verdi', 'Milano', 'giulia.verdi@example.com'),
('Luca', 'Bianchi', 'Torino', 'luca.bianchi@example.com'),
('Anna', 'Neri', 'Roma', 'anna.neri@example.com'),
('Giovanni', 'Gialli', 'Napoli', 'giovanni.gialli@example.com'),
('Marco', 'Azzurri', 'Roma', 'marco.azzurri@example.com'),
('Laura', 'Marroni', 'Milano', 'laura.marroni@example.com'),
('Alessandro', 'Grigi', 'Torino', 'alessandro.grigi@example.com'),
('Sofia', 'Rosa', 'Firenze', 'sofia.rosa@example.com'),
('Lorenzo', 'Viola', 'Bologna', 'lorenzo.viola@example.com'),
('Beatrice', 'Arancioni', 'Roma', 'beatrice.arancioni@example.com'),
('Matteo', 'Blu', 'Milano', 'matteo.blu@example.com'),
('Chiara', 'Celesti', 'Torino', 'chiara.celesti@example.com'),
('Riccardo', 'Verdi', 'Napoli', 'riccardo.verdi@example.com'),
('Elena', 'Gialli', 'Roma', 'elena.gialli@example.com'),
('Federico', 'Azzurri', 'Milano', 'federico.azzurri@example.com'),
('Valentina', 'Marroni', 'Torino', 'valentina.marroni@example.com'),
('Davide', 'Grigi', 'Firenze', 'davide.grigi@example.com'),
('Sara', 'Rosa', 'Bologna', 'sara.rosa@example.com'),
('Francesco', 'Viola', 'Roma', 'francesco.viola@example.com'),
('Alessia', 'Arancioni', 'Milano', 'alessia.arancioni@example.com'),
('Andrea', 'Blu', 'Torino', 'andrea.blu@example.com'),
('Giorgia', 'Celesti', 'Napoli', 'giorgia.celesti@example.com'),
('Emanuele', 'Verdi', 'Roma', 'emanuele.verdi@example.com'),
('Alice', 'Gialli', 'Milano', 'alice.gialli@example.com'),
('Filippo', 'Azzurri', 'Torino', 'filippo.azzurri@example.com'),
('Martina', 'Marroni', 'Firenze', 'martina.marroni@example.com'),
('Stefano', 'Grigi', 'Bologna', 'stefano.grigi@example.com'),
('Nicole', 'Rosa', 'Roma', 'nicole.rosa@example.com'),
('Gabriele', 'Viola', 'Milano', 'gabriele.viola@example.com'),
('Aurora', 'Arancioni', 'Torino', 'aurora.arancioni@example.com'),
('Tommaso', 'Blu', 'Napoli', 'tommaso.blu@example.com'),
('Emma', 'Celesti', 'Roma', 'emma.celesti@example.com'),
('Leonardo', 'Verdi', 'Milano', 'leonardo.verdi@example.com'),
('Ginevra', 'Gialli', 'Torino', 'ginevra.gialli@example.com'),
('Edoardo', 'Azzurri', 'Firenze', 'edoardo.azzurri@example.com'),
('Giulia', 'Marroni', 'Bologna', 'giulia.marroni@example.com'),
('Mattia', 'Grigi', 'Roma', 'mattia.grigi@example.com'),
('Arianna', 'Rosa', 'Milano', 'arianna.rosa@example.com'),
('Samuel', 'Viola', 'Torino', 'samuel.viola@example.com'),
('Rebecca', 'Arancioni', 'Napoli', 'rebecca.arancioni@example.com'),
('Christian', 'Blu', 'Roma', 'christian.blu@example.com'),
('Noemi', 'Celesti', 'Milano', 'noemi.celesti@example.com'),
('Daniele', 'Verdi', 'Torino', 'daniele.verdi@example.com'),
('Angelica', 'Gialli', 'Firenze', 'angelica.gialli@example.com');

-- Creazione della tabella prodotti
CREATE TABLE prodotti (
  id INT PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(50) NOT NULL,
  prezzo DECIMAL(10, 2) NOT NULL,
  categoria VARCHAR(50)
);

-- Inserimento di dati nella tabella prodotti (50 record)
INSERT INTO prodotti (nome, prezzo, categoria) VALUES
('Laptop', 1200.00, 'Informatica'),
('Smartphone', 800.00, 'Telefonia'),
('Tablet', 300.00, 'Informatica'),
('TV', 500.00, 'Elettronica'),
('Fotocamera', 400.00, 'Fotografia'),
('Mouse', 20.00, 'Informatica'),
('Tastiera', 80.00, 'Informatica'),
('Monitor', 300.00, 'Informatica'),
('Stampante', 150.00, 'Informatica'),
('Cuffie', 100.00, 'Audio'),
('Altoparlante Bluetooth', 50.00, 'Audio'),
('Scheda Video', 400.00, 'Informatica'),
('SSD', 100.00, 'Informatica'),
('Hard Disk', 80.00, 'Informatica'),
('RAM', 60.00, 'Informatica'),
('Webcam', 50.00, 'Informatica'),
('Microfono', 80.00, 'Audio'),
('Chitarra', 200.00, 'Strumenti Musicali'),
('Pianoforte', 5000.00, 'Strumenti Musicali'),
('Violino', 300.00, 'Strumenti Musicali'),
('Batteria', 800.00, 'Strumenti Musicali'),
('Amplificatore', 300.00, 'Audio'),
('Mixer', 200.00, 'Audio'),
('Console', 400.00, 'Videogiochi'),
('Videogioco', 60.00, 'Videogiochi'),
('Controller', 80.00, 'Videogiochi'),
('VR Headset', 300.00, 'Videogiochi'),
('Drone', 1000.00, 'Elettronica'),
('Smartwatch', 200.00, 'Telefonia'),
('Ebook Reader', 150.00, 'Informatica'),
('Lampada Smart', 80.00, 'Domotica'),
('Termostato Smart', 120.00, 'Domotica'),
('Aspirapolvere Robot', 300.00, 'Domotica'),
('Friggitrice ad Aria', 100.00, 'Elettrodomestici'),
('Forno a Microonde', 80.00, 'Elettrodomestici'),
('Lavatrice', 500.00, 'Elettrodomestici'),
('Asciugatrice', 400.00, 'Elettrodomestici'),
('Lavastoviglie', 600.00, 'Elettrodomestici'),
('Macchina da Caffè', 200.00, 'Elettrodomestici'),
('Frullatore', 50.00, 'Elettrodomestici'),
('Tostapane', 30.00, 'Elettrodomestici'),
('Bilancia', 20.00, 'Salute e Benessere'),
('Termometro', 15.00, 'Salute e Benessere'),
('Misuratore di Pressione', 80.00, 'Salute e Benessere'),
('Smartband', 100.00, 'Salute e Benessere'),
('Tapis Roulant', 800.00, 'Sport e Fitness'),
('Cyclette', 300.00, 'Sport e Fitness');

-- Creazione della tabella ordini
CREATE TABLE ordini (
  id INT PRIMARY KEY AUTO_INCREMENT,
  cliente_id INT,
  prodotto_id INT,
  quantita INT,
  data_ordine DATE,
  FOREIGN KEY (cliente_id) REFERENCES clienti(id),
  FOREIGN KEY (prodotto_id) REFERENCES prodotti(id)
);

-- Inserimento di dati nella tabella ordini
INSERT INTO ordini (cliente_id, prodotto_id, quantita, data_ordine) VALUES
(1, 1, 1, '2023-01-15'),
(2, 3, 2, '2023-02-20'),
(3, 5, 1, '2023-03-10'),
(4, 2, 3, '2023-04-05'),
(5, 4, 1, '2023-05-12'),
(1, 3, 2, '2023-06-18'),
(2, 1, 1, '2023-07-22'),
(3, 4, 3, '2023-08-11'),
(4, 5, 2, '2023-09-03'),
(5, 2, 1, '2023-10-17'),
(1, 1, 1, '2023-11-21'),
(2, 3, 2, '2023-12-09'),
(3, 5, 1, '2024-01-02'),
(4, 2, 3, '2024-02-14'),
(5, 4, 1, '2024-03-08'),
(1, 3, 2, '2024-04-11'),
(2, 1, 1, '2024-05-15'),
(3, 4, 3, '2024-06-22'),
(4, 5, 2, '2024-07-18'),
(5, 2, 1, '2024-08-01'),
(6, 8, 1, '2024-09-10'),
(7, 10, 2, '2024-10-05'),
(8, 12, 1, '2024-11-12'),
(9, 14, 3, '2024-12-18'),
(10, 16, 1, '2025-01-22'),
(11, 18, 2, '2025-02-09');